server {
    listen 8000;
    server_name localhost;

    # dist をそのまま配信
    #root /usr/share/nginx/html;

    # 静的ファイルはそのまま返す
    location / {
        proxy_pass http://host.docker.internal:5173;
    }

    # API は backend に流す
    # 
    location /api {
        # backendをDockerで起動し、デバッガをアタッチする場合、Dockerで実行しているbackendへ。
        proxy_pass http://backend:8080;
        # backendをWSL上で直接起動する場合、ホスト上のbackendへ、
        #proxy_pass http://host.docker.internal:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # BASE64URL エンコード済みの payload を渡す
        #proxy_set_header x-amzn-oidc-data "eyJzdWIiOiJ0ZXN0LXVzZXIiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0";
        #proxy_set_header x-amzn-oidc-identity  "test-user";
        #proxy_set_header x-amzn-oidc-accesstoken "dummy-access-token";
        # claims は JSON のまま（これは BASE64URL ではない）
        #proxy_set_header x-amzn-oidc-claims '{"email":"test@example.com","email_verified":true}';
    }

    # テスト中はこのヘッダの値が固定になってしまうため、認可のテストができない。と思っていた時代がありました。
    # cookieにより、ここで付与するヘッダの値を変更することができるらしい。
    # こんな感じで設定しておく。
    # map $cookie_oidc_user $oidc_data {
    #     default "eyJzdWIiOiJ0ZXN0LXVzZXIiLCJyb2xlcyI6WyJ1c2VyIl19"; # user
    #     admin   "eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbImFkbWluIl19";   # admin
    #     guest   "eyJzdWIiOiJndWVzdCIsInJvbGVzIjpbXX0";            # guest (権限なし)
    # }
    # proxyヘッダの設定
    #        proxy_set_header x-amzn-oidc-data $oidc_data;
    # Playwrightでcookieをセット。
    # await context.addCookies([
    #   { name: "oidc-user", value: "admin", domain: "nginx" }
    # ]);
    # これで認証情報を切り替えることで認可関連のテストを行うことができる。
    # 
}
