# local環境での設定を記述してください。
# 実際に読み込まれるのは、config.yamlです。開発中はこのファイルをconfig.yamlに上書きして使うこと。
# 開発環境のみで使う値はここに設定するのではなく、npm run dev で起動するときに環境変数を指定するようにしたほうがいいでしょう。
# AWSの環境では、CloudFrontがホストするため、環境変数をつかうことができません。そのため、AWS上では起動時にこのファイルから読み込むようになっています。

env: dev
