# docker compose run --rm flyway
name: jester-playground

services:
  flyway:
    # 公式のものがWAS Punlic ECRにない。
    image: flyway/flyway
    container_name: flyway_migration
    networks:
      - jester
    volumes:
      - ./src/main/resources/db:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:mysql://db:3306/jester?useSSL=false&allowPublicKeyRetrieval=true
      - FLYWAY_USER=jester
      - FLYWAY_PASSWORD=jester
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql/migrations,filesystem:/flyway/sql/repeatables

networks:
  jester:
    external: true
    name: jester
