# AWS Parameter Storeに登録する値。
# スクリプトでPrefixを付与して登録するため、ここではPrefixを付与しない。
# キーはプロパティファイルにあるキーと同一にすること。
# AWS環境で、環境別に設定する必要がないプロパティ（例。ログレベル）は、プロパティファイルに直接記述してもよい。
spring.datasource.hikari.data-source-properties.wrapperPlugins=iam,failover,efm2
spring.datasource.driver-class-name=software.amazon.jdbc.Driver
spring.datasource.url=jdbc:aws-wrapper:mysql://enchanter-rds.cx2c4awkaqk4.ap-northeast-1.rds.amazonaws.com:3306/jester?useSSL=true&requireSSL=true&verifyServerCertificate=true
spring.datasource.hikari.data-source-properties.wrapperPlugins=iam,failover,efm2
spring.datasource.username=jester_iam
# IAM認証を使用するので、設定する必要はないが、ダミーの値を設定しておく。
spring.datasource.password=jester

# AWS Cognitoの設定値。
aws.cognito.issuer=https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_OgaYp5bZA
aws.cognito.audience=6d0hpf8q6tb3lmmcerberi3969
aws.cognito.url=https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_OgaYp5bZA

# scopeをprovidedにしているので、AWS環境ではFlywayの依存関係がない。
#spring.flyway.enabled=false
