# AWS環境用の設定ファイル。パラメータストアとシークレットマネージャーから値を取得する。
# /parameters にあるパラメータストアの値を登録しておくこと。
# AWS環境で、環境別に設定する必要がないプロパティ（例。ログレベル）は、プロパティファイルに直接記述してもよい。
# SPRING_PROFILES_ACTIVE=awsを設定することで、AWS環境用の設定ファイルとして読み込まれる。この値は固定。
# 環境別にするには、環境変数ENVを設定する。ENVの値は、パラメータストアとシークレットマネージャーのキーのprefixに使用される。

spring.application.name=backend
spring.docker.compose.enabled=false

# AWSでの設定。
# spring-profile-active=awsを設定。
spring.config.activate.on-profile=aws

logging.level.root=INFO
logging.level.com.unreliableforge=INFO
logging.pattern=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{requestId}] %-5level %logger{36} - %msg%n

# 値はパラメータストアとシークレットマネージャーから取得するようになっています。
# prefixは、/jester/backend/${ENV}/ です。

# IAM認証を使用するため、SecretsManagerを使う予定はないが、一応使用しておく。
# parameter storeの場合は、 パラメータストアのキーのprefix
# secrets managerの場合は、secrets managerの名前。JSONのキーを指定する。
# 両方に同じ値がある場合、後ろにあるほうで上書き。
spring.config.import=aws-parameterstore:/jester/backend/${ENV}/,aws-secretsmanager:/jester/backend/${ENV}/

# driver classはawsのものを使うため、この設定はfalseでよい。
#spring.datasource.driver-class-name=software.amazon.jdbc.Driver
#spring.datasource.hikari.data-source-properties.awsIam=false

# spring.config.importを使用する。パラメータストアとシークレットマネージャーにはプロパティと同じ名前で登録するため、プロパティファイル内での設定は不要。
#spring.datasource.driver-class-name=software.amazon.jdbc.Driver
#spring.datasource.url=${spring.datasource.url}
#spring.datasource.username=${db/username}
#spring.datasource.password=${db/password}

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=lax

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# JWTのissとaudがこれと一致すること。URLはJWTの検証に使用する。
#aws.cognito.issuer=${cognito/iss}
#aws.cognito.audience=${cognito/aud}
#aws.cognito.url=${cognito/url}

