# ローカル環境(docker container)用プロパティ。
# aws sso login 
# としておくと、パラメータストアやシークレットマネージャーの値を使用することもできる。
# ローカルは開発環境が個人ごとに異なる可能性がるため、パラメータストアやシークレットマネージャーの使用は推奨しない。
# APIキーなどの機密情報を扱う場合、シークレットマネージャーに記述すること。

spring.application.name=backend
spring.docker.compose.enabled=false

logging.level.root=INFO
logging.level.com.unreliableforge=DEBUG
logging.pattern=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{requestId}] %-5level %logger{36} - %msg%n

# 1. JavaScriptからのアクセスを禁止する (XSS対策)
server.servlet.session.cookie.http-only=true
# 2. HTTPS通信時のみCookieを送信する (盗聴対策)
# ※ローカル開発環境でHTTPを使う場合は false にするか、環境ごとに切り替えてください
server.servlet.session.cookie.secure=false
# 3. 他サイトからの不正なリクエストで送信されないようにする (CSRF対策)
# 値には Lax または Strict を指定できます
server.servlet.session.cookie.same-site=lax

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/jester
spring.datasource.username=jester
spring.datasource.password=jester
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# JWTのissとaudがこれと一致すること。URLはJWTの検証に使用する。
aws.cognito.issuer=issure-00
aws.cognito.audience=audience-00
aws.cognito.url=CognitoEndpointURL
