# ローカル環境(docker container)用プロパティ。
# ローカルは開発環境が個人ごとに異なる可能性がるため、パラメータストアやシークレットマネージャーの使用は推奨しない。
# APIキーなどの機密情報を扱う場合、シークレットマネージャーに記述すること。

spring.application.name=backend
spring.docker.compose.enabled=false

logging.level.root=DEBUG
logging.level.com.unreliableforge=DEBUG
logging.pattern=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{requestId}] %-5level %logger{36} - %msg%n

# アクセスログはCloudFrontで出力する。
# server.tomcat.accesslog.enabled=true
# server.tomcat.accesslog.pattern=%h %l %u "%r" %s %b "%{User-Agent}i"
# server.tomcat.accesslog.directory=/dev/stdout
# server.tomcat.accesslog.prefix=console
# server.tomcat.accesslog.suffix=
# server.tomcat.accesslog.file-date-format=

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax

# ローカル開発環境用のデータソース設定.
# ホスト名は、WSLからはlocalhot. コンテナ内からはサービス名となる。
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/jester
spring.datasource.username=jester
spring.datasource.password=jester
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# JWTのissとaudがこれと一致すること。URLはJWTの検証に使用する。
aws.cognito.issuer=issure-00
aws.cognito.audience=audience-00
aws.cognito.url=CognitoEndpointURL
